apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pythondemo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/mdkumarmca/digit7-product-api-service   #Write repository name
    #argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-secret
    argocd-image-updater.argoproj.io/myalias.pull-secret: pullsecret:argocd/argocd-docker-secret  # You can remove this annotation if you have already configured the gcr secret and are using the same secret to retrieve all GCR images in your deployments.
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest #There are several ways to update the image, but I'm using digest.
    argocd-image-updater.argoproj.io/write-back-method: git  # We don't need the secret as mentioned in argocd doc because we already set it up via argocd console if you're using the same git repo.
    argocd-image-updater.argoproj.io/git-branch: main 
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
  labels:
    name: pythondemo

spec:
  project: default

  source:
    #repoURL: git@github.com:venkatd7/kub-argocd.git
    repoURL: git@github.com:DhilipKumarMarimuthu/digitmart.edge.devops.git
    targetRevision: HEAD  
    path: dev # path of the kubernetes application code means where you stored deployment.yaml, service.yaml etc

    
  destination:
    server: https://kubernetes.default.svc  # if you want to deploy application in the same cluster where argocd server is running if thats diffrent then use cluster IP address.
    namespace: pythondemo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
